# Generated by Django 4.2.4 on 2023-09-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(max_length=45)),
                ('titulocampanha', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('datainicio', models.DateTimeField()),
                ('datatermino', models.DateTimeField()),
                ('valormeta', models.IntegerField()),
                ('imagem1', models.CharField(max_length=250, null=True)),
                ('imagem2', models.CharField(max_length=250, null=True)),
                ('imagem3', models.CharField(max_length=250, null=True)),
                ('imagem4', models.CharField(max_length=250, null=True)),
                ('imagem5', models.CharField(max_length=250, null=True)),
                ('imagem6', models.CharField(max_length=250, null=True)),
                ('imagem7', models.CharField(max_length=250, null=True)),
                ('imagem8', models.CharField(max_length=250, null=True)),
                ('background', models.CharField(max_length=250, null=True)),
                ('logo', models.CharField(max_length=250, null=True)),
                ('texto1', models.CharField(max_length=450, null=True)),
                ('texto2', models.CharField(max_length=450, null=True)),
                ('texto3', models.CharField(max_length=450, null=True)),
                ('texto4', models.CharField(max_length=450, null=True)),
                ('texto5', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('nomeinstituicao', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('emailinstituicao', models.CharField(max_length=45)),
                ('multas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=160, null=True)),
                ('nascimento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('numerocasa', models.CharField(max_length=4, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('país', models.CharField(max_length=45, null=True)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.CharField(max_length=45)),
                ('cartao_numerocartao', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=45)),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campanha')),
                ('usuario_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='usuario_iddoador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
